import { db } from "@workspace/db";
import { categoriesTable as categories, productsTable as products, bannersTable as banners } from "@workspace/db";

async function seed() {
  console.log("Seeding bakery data...");

  const existingCats = await db.select().from(categories);
  if (existingCats.length > 0) {
    console.log("Database already seeded. Use 'reseed' to overwrite.");
    return;
  }

  const [cakes, cookies, pastries, breads, traditionalSweets, localDelights] = await db
    .insert(categories)
    .values([
      { name: "Celebration Cakes", slug: "cakes", description: "Custom cakes for every occasion", sortOrder: 1 },
      { name: "Cookies & Biscuits", slug: "cookies", description: "Hand-decorated artisan cookies", sortOrder: 2 },
      { name: "Pastries & Desserts", slug: "pastries", description: "Freshly baked pastries and desserts", sortOrder: 3 },
      { name: "Artisan Breads", slug: "breads", description: "Sourdough and specialty breads", sortOrder: 4 },
      { name: "Traditional Sweets", slug: "traditional-sweets", description: "Authentic desi halwas and barfis", sortOrder: 5 },
      { name: "Local Delights", slug: "local-delights", description: "Classic tea-time snacks and biscuits", sortOrder: 6 },
    ])
    .returning();

  console.log("Categories created.");

  await db.insert(products).values([
    // ── Celebration Cakes (8) ──
    {
      name: "Classic Vanilla Birthday Cake",
      slug: "classic-vanilla-birthday-cake",
      description: "A timeless vanilla sponge layered with silky buttercream frosting. Perfect for any celebration.",
      basePrice: "2500.00",
      categoryId: cakes.id,
      imageUrls: JSON.stringify(["/images/vanilla_birthday_cake_1778333832089.webp"]),
      variants: JSON.stringify([
        { name: "Size", type: "size", options: [{ label: "6 inch (serves 8)", priceAdjustment: 0 }, { label: "8 inch (serves 16)", priceAdjustment: 800 }, { label: "10 inch (serves 24)", priceAdjustment: 1500 }] },
      ]),
      addons: JSON.stringify([{ name: "Gold Drip", price: 500 }]),
      allowCustomMessage: true,
      isVisible: true,
      isAvailable: true,
    },
    {
      name: "Chocolate Fudge Indulgence Cake",
      slug: "chocolate-fudge-cake",
      description: "Rich dark chocolate sponge with velvety ganache — a chocoholic's dream.",
      basePrice: "3200.00",
      categoryId: cakes.id,
      imageUrls: JSON.stringify(["/images/chocolate_fudge_cake_1778333847277.webp"]),
      variants: JSON.stringify([]),
      addons: JSON.stringify([]),
      allowCustomMessage: true,
      isVisible: true,
      isAvailable: true,
    },
    {
      name: "Red Velvet Dream Cake",
      slug: "red-velvet-dream-cake",
      description: "Velvety red sponge with luscious cream cheese frosting.",
      basePrice: "3000.00",
      categoryId: cakes.id,
      imageUrls: JSON.stringify(["/images/red_velvet_cake_1778333860945.webp"]),
      variants: JSON.stringify([]),
      addons: JSON.stringify([]),
      allowCustomMessage: true,
      isVisible: true,
      isAvailable: true,
    },
    {
      name: "Pineapple Gateau",
      slug: "pineapple-gateau",
      description: "A Pakistani bakery classic — light sponge layers filled with pineapple cream.",
      basePrice: "2800.00",
      categoryId: cakes.id,
      imageUrls: JSON.stringify(["/images/pineapple_gateau_1778333876444.webp"]),
      variants: JSON.stringify([]),
      addons: JSON.stringify([]),
      allowCustomMessage: true,
      isVisible: true,
      isAvailable: true,
    },
    {
      name: "Black Forest Cake",
      slug: "black-forest-cake",
      description: "Layers of dark chocolate sponge, cherries, and whipped cream.",
      basePrice: "3200.00",
      categoryId: cakes.id,
      imageUrls: JSON.stringify(["/images/black_forest_cake_1778333897744.webp"]),
      variants: JSON.stringify([]),
      addons: JSON.stringify([]),
      allowCustomMessage: true,
      isVisible: true,
      isAvailable: true,
    },
    {
      name: "Tres Leches Cake",
      slug: "tres-leches-cake",
      description: "Ultra-moist sponge soaked in three kinds of milk.",
      basePrice: "3500.00",
      categoryId: cakes.id,
      imageUrls: JSON.stringify(["/images/tres_leches_cake_1778333913272.webp"]),
      variants: JSON.stringify([]),
      addons: JSON.stringify([]),
      allowCustomMessage: true,
      isVisible: true,
      isAvailable: true,
    },
    {
      name: "Rose & Pistachio Cake",
      slug: "rose-pistachio-cake",
      description: "Fragrant rose-water infused sponge with pistachio buttercream.",
      basePrice: "3800.00",
      categoryId: cakes.id,
      imageUrls: JSON.stringify(["/images/rose_pistachio_cake_1778334186656.webp"]),
      variants: JSON.stringify([]),
      addons: JSON.stringify([]),
      allowCustomMessage: true,
      isVisible: true,
      isAvailable: true,
    },
    {
      name: "New York Cheesecake",
      slug: "new-york-cheesecake",
      description: "Dense, creamy, and smooth baked to perfection.",
      basePrice: "3200.00",
      categoryId: cakes.id,
      imageUrls: JSON.stringify(["/images/new_york_cheesecake_1778333976171.webp"]),
      variants: JSON.stringify([]),
      addons: JSON.stringify([]),
      allowCustomMessage: false,
      isVisible: true,
      isAvailable: true,
    },

    // ── Cookies & Biscuits (3) ──
    {
      name: "Classic Butter Cookies (12 pack)",
      slug: "butter-cookies-12",
      description: "Buttery melt-in-your-mouth cookies.",
      basePrice: "1200.00",
      categoryId: cookies.id,
      imageUrls: JSON.stringify(["/images/butter_cookies_1778333992085.webp"]),
      variants: JSON.stringify([]),
      addons: JSON.stringify([]),
      allowCustomMessage: false,
      isVisible: true,
      isAvailable: true,
    },
    {
      name: "Macaron Box (12 pieces)",
      slug: "macaron-box-12",
      description: "Delicate French macarons in seasonal flavours.",
      basePrice: "1800.00",
      categoryId: cookies.id,
      imageUrls: JSON.stringify(["/images/macaron_box_1778334007614.webp"]),
      variants: JSON.stringify([]),
      addons: JSON.stringify([]),
      allowCustomMessage: false,
      isVisible: true,
      isAvailable: true,
    },
    {
      name: "Brownie Box (9 pieces)",
      slug: "brownie-box-9",
      description: "Fudgy, rich chocolate brownies baked with Belgian chocolate.",
      basePrice: "1500.00",
      categoryId: cookies.id,
      imageUrls: JSON.stringify(["/images/brownie_box_1778334027943.webp"]),
      variants: JSON.stringify([]),
      addons: JSON.stringify([]),
      allowCustomMessage: false,
      isVisible: true,
      isAvailable: true,
    },

    // ── Pastries & Desserts (3) ──
    {
      name: "Butter Croissant",
      slug: "butter-croissant",
      description: "Flaky, golden, made with pure European butter.",
      basePrice: "350.00",
      categoryId: pastries.id,
      imageUrls: JSON.stringify(["/images/butter_croissant_1778334054088.webp"]),
      variants: JSON.stringify([]),
      addons: JSON.stringify([]),
      allowCustomMessage: false,
      isVisible: true,
      isAvailable: true,
    },
    {
      name: "Mini Cupcakes (6 pack)",
      slug: "mini-cupcakes-6",
      description: "Perfectly portioned mini cupcakes with pillowy frosting swirls.",
      basePrice: "900.00",
      categoryId: pastries.id,
      imageUrls: JSON.stringify(["/images/mini_cupcakes_1778334203343.webp"]),
      variants: JSON.stringify([]),
      addons: JSON.stringify([]),
      allowCustomMessage: false,
      isVisible: true,
      isAvailable: true,
    },
    {
      name: "Swiss Roll",
      slug: "swiss-roll",
      description: "Soft sponge rolled with fresh cream and jam.",
      basePrice: "1200.00",
      categoryId: pastries.id,
      imageUrls: JSON.stringify(["/images/swiss_roll_1778334226285.webp"]),
      variants: JSON.stringify([]),
      addons: JSON.stringify([]),
      allowCustomMessage: false,
      isVisible: true,
      isAvailable: true,
    },

    // ── Artisan Breads (1) ──
    {
      name: "Sourdough Boule",
      slug: "sourdough-boule",
      description: "Long-fermented sourdough with a crisp crust.",
      basePrice: "900.00",
      categoryId: breads.id,
      imageUrls: JSON.stringify(["/images/sourdough_boule_1778334243673.webp"]),
      variants: JSON.stringify([]),
      addons: JSON.stringify([]),
      allowCustomMessage: false,
      isVisible: true,
      isAvailable: true,
    },

    // ── Traditional Sweets (5) ──
    {
      name: "Coconut Halwa | کوکو نٹ حلوا",
      slug: "coconut-halwa",
      description: "Authentic and rich traditional Coconut Halwa.",
      basePrice: "800.00",
      categoryId: traditionalSweets.id,
      imageUrls: JSON.stringify(["/images/coconut_halwa_1778357656534.webp"]),
      variants: JSON.stringify([]),
      addons: JSON.stringify([]),
      allowCustomMessage: false,
      isVisible: true,
      isAvailable: true,
    },
    {
      name: "Badam Barfi | بادام برفی",
      slug: "badam-barfi",
      description: "Premium Badam Barfi (Almond Fudge) made with high-quality almonds.",
      basePrice: "1200.00",
      categoryId: traditionalSweets.id,
      imageUrls: JSON.stringify(["/images/badam_barfi_1778357675252.webp"]),
      variants: JSON.stringify([]),
      addons: JSON.stringify([]),
      allowCustomMessage: false,
      isVisible: true,
      isAvailable: true,
    },
    {
      name: "Khajoor Halwa | کھجور حلوہ",
      slug: "khajoor-halwa",
      description: "Healthy, energy-boosting Khajoor Halwa made from premium dates.",
      basePrice: "1000.00",
      categoryId: traditionalSweets.id,
      imageUrls: JSON.stringify(["/images/khajoor_halwa_1778357689844.webp"]),
      variants: JSON.stringify([]),
      addons: JSON.stringify([]),
      allowCustomMessage: false,
      isVisible: true,
      isAvailable: true,
    },
    {
      name: "Khoya Barfi | کھویا برفی",
      slug: "khoya-barfi",
      description: "Classic melt-in-the-mouth Khoya Barfi.",
      basePrice: "900.00",
      categoryId: traditionalSweets.id,
      imageUrls: JSON.stringify(["/images/khoya_barfi_1778357705562.webp"]),
      variants: JSON.stringify([]),
      addons: JSON.stringify([]),
      allowCustomMessage: false,
      isVisible: true,
      isAvailable: true,
    },
    {
      name: "Milk Cake | ملک کیک",
      slug: "milk-cake",
      description: "Traditional grainy milk cake, sweet and rich.",
      basePrice: "1100.00",
      categoryId: traditionalSweets.id,
      imageUrls: JSON.stringify(["/images/khoya_barfi_1778357705562.webp"]),
      variants: JSON.stringify([]),
      addons: JSON.stringify([]),
      allowCustomMessage: false,
      isVisible: true,
      isAvailable: true,
    },

    // ── Local Delights (4) ──
    {
      name: "Cake Rus | کیک رس",
      slug: "cake-rus",
      description: "Crispy, golden, and perfectly sweetened traditional Cake Rus.",
      basePrice: "400.00",
      categoryId: localDelights.id,
      imageUrls: JSON.stringify(["/images/cake_rus_1778357719114.webp"]),
      variants: JSON.stringify([]),
      addons: JSON.stringify([]),
      allowCustomMessage: false,
      isVisible: true,
      isAvailable: true,
    },
    {
      name: "Special Khatai Biscuit | اسپیشل خطائی بسکٹ",
      slug: "special-khatai-biscuit",
      description: "Authentic Special Nan Khatai biscuits.",
      basePrice: "450.00",
      categoryId: localDelights.id,
      imageUrls: JSON.stringify(["/images/special_khatai_1778357733700.webp"]),
      variants: JSON.stringify([]),
      addons: JSON.stringify([]),
      allowCustomMessage: false,
      isVisible: true,
      isAvailable: true,
    },
    {
      name: "Baqar Khani | باقر خانی",
      slug: "baqar-khani",
      description: "Flaky, layered, and crispy traditional Baqar Khani.",
      basePrice: "350.00",
      categoryId: localDelights.id,
      imageUrls: JSON.stringify(["/images/baqar_khani_1778357752856.webp"]),
      variants: JSON.stringify([]),
      addons: JSON.stringify([]),
      allowCustomMessage: false,
      isVisible: true,
      isAvailable: true,
    },
    {
      name: "Coconut Biscuit | کوکو نٹ بسکٹ",
      slug: "coconut-biscuit",
      description: "Crunchy tea-time biscuits loaded with toasted coconut flakes.",
      basePrice: "450.00",
      categoryId: localDelights.id,
      imageUrls: JSON.stringify(["/images/coconut_biscuit_1778357767929.webp"]),
      variants: JSON.stringify([]),
      addons: JSON.stringify([]),
      allowCustomMessage: false,
      isVisible: true,
      isAvailable: true,
    },
  ]);

  await db.insert(banners).values([
    {
      title: "Fresh from the Oven",
      subtitle: "Custom cakes, artisan cookies, and seasonal pastries — made to order.",
      imageUrl: "/images/hero_banner_1_1778334264126.webp",
      linkUrl: "/shop",
      isActive: true,
      sortOrder: 1,
    },
    {
      title: "Order Your Dream Cake",
      subtitle: "Birthdays, weddings, or just because.",
      imageUrl: "/images/hero_banner_1_1778334264126.webp",
      linkUrl: "/shop",
      isActive: true,
      sortOrder: 2,
    },
  ]);

  console.log("✅ Seed complete! 24 products created.");
}

seed().catch((err) => {
  console.error("Seed error:", err);
  process.exit(1);
});
